version: '3.9'

services:
  db:
    image: postgres:13
    container_name: fastapi_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
